title: DS Portfolio
# logo: /Images/profilephoto.jpg  ‚Üê Comment this out or remove it for now
description: A sample histogram from my data science project
show_downloads: true
theme: jekyll-theme-minimal
